export const SELECT_DAY = 'SELECT_DAY';
export const SELECT_PREV_MONTH = 'SELECT_PREV_MONTH';
export const SELECT_NEXT_MONTH = 'SELECT_NEXT_MONTH';

export const CREATE_REMINDER = 'CREATE_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
